CUDA_VISIBLE_DEVICES=0 python src/train_sft.py \
    --do_train \
    --finetuning_type lora \
    --output_dir "./output" \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 5e-5 \
    --num_train_epochs 3.0 \
    --fp16